// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9q7OYknF_B0736W4FDVjvY3QbbQWbp5Q',
    appId: '1:448234566648:web:995d3fac4beff46df11c0d',
    messagingSenderId: '448234566648',
    projectId: 'lapar-manten',
    authDomain: 'lapar-manten.firebaseapp.com',
    storageBucket: 'lapar-manten.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Du6xLN4BlaEYVG7GyeLbu5FNroMV4Vs',
    appId: '1:448234566648:android:e2eb05bb8f54b2b5f11c0d',
    messagingSenderId: '448234566648',
    projectId: 'lapar-manten',
    storageBucket: 'lapar-manten.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYt-lyl3Cj-iDyg30CoseDobCNasxK8U',
    appId: '1:448234566648:ios:77eb55b47c9541e8f11c0d',
    messagingSenderId: '448234566648',
    projectId: 'lapar-manten',
    storageBucket: 'lapar-manten.firebasestorage.app',
    iosBundleId: 'com.example.laparMantenDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYt-lyl3Cj-iDyg30CoseDobCNasxK8U',
    appId: '1:448234566648:ios:77eb55b47c9541e8f11c0d',
    messagingSenderId: '448234566648',
    projectId: 'lapar-manten',
    storageBucket: 'lapar-manten.firebasestorage.app',
    iosBundleId: 'com.example.laparMantenDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9q7OYknF_B0736W4FDVjvY3QbbQWbp5Q',
    appId: '1:448234566648:web:832db0064d280abef11c0d',
    messagingSenderId: '448234566648',
    projectId: 'lapar-manten',
    authDomain: 'lapar-manten.firebaseapp.com',
    storageBucket: 'lapar-manten.firebasestorage.app',
  );
}
